name: Create RPM

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    name: Build RPM package from source
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install RPM build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential rpm elfutils file gnupg

      - name: Prep environment
        run: |
          mkdir -p hello-1.0 SOURCES SPECS
          cp Makefile hello.c hello-1.0/
          tar cvfz SOURCES/hello-1.0.tar.gz hello-1.0
          cp hello.spec SPECS/

      - name: Build RPM
        run: rpmbuild -ba --clean --define "_topdir ${PWD}" SPECS/hello.spec

      - name: Sign RPM
        env:
          GPG: ${{ secrets.GPG }}
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          gpgconf --kill gpg-agent || true

          echo "$GPG" | gpg --batch --import

          KEY_FINGERPRINT=$(gpg --list-secret-keys --with-colons | grep '^fpr:' | head -n1 | cut -d: -f10)

          mkdir -p ~/.config/rpm
          cat << EOF > ~/.config/rpm/macros
          %_signature gpg
          %_gpg_path ~/.gnupg
          %_gpgbin /usr/bin/gpg
          %_gpg_name $KEY_FINGERPRINT
          %_openpgp_sign_id $KEY_FINGERPRINT
          EOF
          
          cp ~/.config/rpm/macros ~/.rpmmacros

          rpmsign --addsign RPMS/x86_64/hello-1.0-1.x86_64.rpm

      - name: Verify Signed RPM Metadata
        run: |
          rpm -Kv RPMS/x86_64/hello-1.0-1.x86_64.rpm

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-1.0-1.x86_64.rpm
          path: RPMS/x86_64/hello-1.0-1.x86_64.rpm
