name: Create RPM

on:
  - pull_request
  - push

env:
  package_name: hello
  version: "1.0"

jobs:
  build:
    name: Build RPM package from source
    runs-on: ubuntu-latest
    container: ghcr.io/beatrubi/build-el9/build-el9:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Prep environment
        run: |
          mkdir -p $package_name-$version SOURCES SPECS
          cp Makefile $package_name.c $package_name-$version/
          tar cvfz SOURCES/$package_name-$version.tar.gz $package_name-$version
          cp $package_name.spec SPECS/

      - name: Build RPM
        run: |
          sudo dnf builddep SPECS/$package_name.spec
          rpmbuild -bb --define "_topdir ${PWD}" --define "%_enable_debug_packages 0" SPECS/$package_name.spec

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v7
        with:
          name: RPMS
          path: |
            RPMS/*/*.rpm
            SRPMS/*.rpm
