name: Create RPM

on:
  - pull_request
  - push

env:
  package_name: hello
  version: "1.0"

jobs:
  build:
    name: Build RPM package from source
    runs-on: ubuntu-latest
    container: ghcr.io/beatrubi/build-el9/build-el9:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Prep environment
        run: |
          mkdir -p $package_name-$version SOURCES SPECS
          cp Makefile $package_name.c $package_name-$version/
          tar cvfz SOURCES/$package_name-$version.tar.gz $package_name-$version
          cp $package_name.spec SPECS/

      - name: Build RPM
        run: |
          sudo dnf builddep SPECS/$package_name.spec
          rpmbuild -bb --clean --define "_topdir ${PWD}" --define "debug_package %{nil}" SPECS/$package_name.spec

      - name: Sign RPM
        env:
          GPG: ${{ secrets.GPG }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG" | gpg --batch --no-tty --import
          KEY_FINGERPRINT=$(gpg --list-secret-keys --with-colons | grep '^fpr:' | head -n1 | cut -d: -f10) 
          gpg --armor --export "$KEY_FINGERPRINT" > RPM-GPG-KEY-test
          sudo rpm --import RPM-GPG-KEY-test
          touch /tmp/gpg_passphrase
          if [ -n "$GPG_PASSPHRASE" ]; then
            echo -n "$GPG_PASSPHRASE" > /tmp/gpg_passphrase
          fi
          mkdir -p ~/.config/rpm
          cat << EOF > ~/.config/rpm/macros
          %_signature gpg
          %_gpg_path ~/.gnupg
          %_gpgbin /usr/bin/gpg
          %_openpgp_sign_id $KEY_FINGERPRINT
          %_gpg_name Name %{_openpgp_sign_id}
          %__gpg_sign_cmd %{_gpgbin} --batch --no-tty --pinentry-mode loopback --passphrase-file "$GPG_PASSPHRASE" --no-verbose --no-armor -s -b -o %{__signature_filename} %{__plaintext_filename}
          EOF
          cp ~/.config/rpm/macros ~/.rpmmacros
          rpmsign --addsign RPMS/x86_64/$package_name-$version-1.el9.x86_64.rpm
          rm -f /tmp/gpg_passphrase

      - name: Verify Signed RPM Metadata
        run: |
          rpm -Kv RPMS/x86_64/$package_name-$version-1.el9.x86_64.rpm

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v7
        with:
          name: RPMS
          path: RPMS/x86_64/*.rpm
